---
---
- name: Install NVIDIA GPU operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: gpu-operator-certified
    install_operator_namespace: nvidia-gpu-operator
    install_operator_channel: "{{ ocp4_workload_nvidia_gpu_operator_channel }}"
    install_operator_manage_namespaces:
    - nvidia-gpu-operator
    install_operator_catalog: certified-operators
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_nvidia_gpu_operator_automatic_install_plan_approval }}"
    install_operator_starting_csv: "{{ ocp4_workload_nvidia_gpu_operator_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_nvidia_gpu_operator_use_catalog_snapshot }}"
    install_operator_catalogsource_name: "{{ ocp4_workload_nvidia_gpu_operator_catalogsource_name }}"
    install_operator_catalogsource_namespace: nvidia-gpu-operator
    install_operator_catalogsource_image: "{{ ocp4_workload_nvidia_gpu_operator_catalog_snapshot_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_nvidia_gpu_operator_catalog_snapshot_image_tag }}"

- name: Setup NVIDIA GPU Cluster Policy
  kubernetes.core.k8s:
    state: present
    file: nvidia_gpu_clusterpolicy.json

# Todo: proper check
# - name: 60 second pause
#   ansible.builtin.pause:
#     seconds: 60

# - name: Install NVIDIA GPU Dashboard
#   when: ocp4_workload_nvidia_gpu_setup_create_dashboard | bool
#   ansible.builtin.shell: |
#     if oc get configmap nvidia-dcgm-exporter-dashboard -n openshift-config-managed; then
#       echo "ConfigMap nvidia-dcgm-exporter-dashboard already exists. Skipping creation."
#     else
#       # Get dashboard JSON
#       curl -Lf {{ ocp4_workload_nvidia_gpu_setup_dcgm_exporter_dashboard_url }} -o dcgm-exporter-dashboard.json

#       # Create ConfigMap
#       oc create configmap nvidia-dcgm-exporter-dashboard -n openshift-config-managed --from-file=dcgm-exporter-dashboard.json

#       # Label the ConfigMap
#       oc label configmap nvidia-dcgm-exporter-dashboard -n openshift-config-managed "console.openshift.io/dashboard=true"
#       oc label configmap nvidia-dcgm-exporter-dashboard -n openshift-config-managed "console.openshift.io/odc-dashboard=true"
#       echo "ConfigMap nvidia-dcgm-exporter-dashboard created and labeled."
#     fi
#     oc -n openshift-config-managed get cm nvidia-dcgm-exporter-dashboard --show-labels
