---
# Validate required variables are set
- name: Validate Azure token authentication variables
  when: ocp4_workload_ols_token | bool
  assert:
    that:
      - ocp4_workload_ols_azure_tenant_id is defined
      - ocp4_workload_ols_azure_tenant_id != "changeme"
      - ocp4_workload_ols_main_client_id is defined
      - ocp4_workload_ols_main_client_id != "changeme"
      - ocp4_workload_ols_main_client_secret is defined
      - ocp4_workload_ols_main_client_secret != "changeme"
      - ocp4_workload_ols_azure_group_id is defined
      - ocp4_workload_ols_azure_group_id != "changeme"
      - ocp4_workload_ols_child_app_display_name is defined
      - guid is defined
    fail_msg: "Azure token authentication is enabled but required variables are not properly configured. Please check defaults/main.yaml"

- name: Validate API key authentication variables
  when: not ocp4_workload_ols_token | bool
  assert:
    that:
      - ocp4_workload_ols_api_token is defined
      - ocp4_workload_ols_api_token != "changeme"
      - ocp4_workload_ols_api_token | length > 0
    fail_msg: "API key authentication is enabled but ocp4_workload_ols_api_token is not properly configured. Please check defaults/main.yaml"

- name: Validate AI platform is supported
  when: ocp4_workload_ai_platform is defined
  assert:
    that:
      - ocp4_workload_ai_platform in ['azure', 'openai', 'watson', 'openshiftai']
    fail_msg: "ocp4_workload_ai_platform must be one of: azure, openai, watson, openshiftai"

- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent | bool
