---
# Azure AI Cognitive Services Token Setup
# This file handles Azure AD app registration and token management

- name: Get Token for Master App
  uri:
    url: "https://login.microsoftonline.com/{{ ocp4_workload_ols_azure_tenant_id }}/oauth2/v2.0/token"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    # yamllint disable rule:line-length
    body: "grant_type=client_credentials&client_id={{ ocp4_workload_ols_main_client_id }}&client_secret={{ ocp4_workload_ols_main_client_secret }}&scope=https://graph.microsoft.com/.default"
    # yamllint enable rule:line-length
    return_content: true
    status_code: 200
  register: master_token_response
  until: master_token_response is succeeded
  retries: 3
  delay: 5

- name: Set Main Access Token
  set_fact:
    master_access_token: "{{ master_token_response.json.access_token }}"

- name: Create Child App Registration
  uri:
    url: "https://graph.microsoft.com/v1.0/applications"
    method: POST
    headers:
      Authorization: "Bearer {{ master_access_token }}"
      Content-Type: "application/json"
    body:
      displayName: "{{ ocp4_workload_ols_child_app_display_name }}-{{ guid }}"
      passwordCredentials:
        - displayName: "ChildAppRegistrationSecret"
    body_format: json
    return_content: true
    status_code: 201
  register: child_app_response
  until: child_app_response is succeeded
  retries: 3
  delay: 5

- name: Set Child App ID and Secret
  set_fact:
    _child_app_id: "{{ child_app_response.json.appId }}"
    _child_client_secret: "{{ child_app_response.json.passwordCredentials[0].secretText }}"

- name: Wait for Child App to propagate in Azure AD
  uri:
    url: "https://graph.microsoft.com/v1.0/applications/{{ child_app_response.json.id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ master_access_token }}"
    status_code: 200
  register: app_check
  until: app_check.status == 200
  retries: 12
  delay: 5

- name: Create Service Principal for Child App
  uri:
    url: "https://graph.microsoft.com/v1.0/servicePrincipals"
    method: POST
    headers:
      Authorization: "Bearer {{ master_access_token }}"
      Content-Type: "application/json"
    body:
      appId: "{{ _child_app_id | string }}"
    body_format: json
    return_content: true
    status_code: 201
  register: service_principal_response
  until: service_principal_response is succeeded
  retries: 3
  delay: 5

- name: Set Child Service Principal Object ID
  set_fact:
    _child_service_principal_object_id: "{{ service_principal_response.json.id }}"

- name: Wait for Service Principal to propagate in Azure AD
  uri:
    url: "https://graph.microsoft.com/v1.0/servicePrincipals/{{ _child_service_principal_object_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ master_access_token }}"
    status_code: 200
  register: sp_check
  until: sp_check.status == 200
  retries: 12
  delay: 5

- name: Add Child App to Azure AD Group
  uri:
    url: "https://graph.microsoft.com/v1.0/groups/{{ ocp4_workload_ols_azure_group_id }}/members/$ref"
    method: POST
    headers:
      Authorization: "Bearer {{ master_access_token }}"
      Content-Type: "application/json"
    body:
      "@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/{{ _child_service_principal_object_id }}"
    body_format: json
    return_content: true
    status_code: [201, 204]
  register: group_add_result
  until: group_add_result is succeeded
  retries: 3
  delay: 5

- name: Wait for Group Membership to propagate
  uri:
    url: "https://graph.microsoft.com/v1.0/servicePrincipals/{{ _child_service_principal_object_id }}/memberOf"
    method: GET
    headers:
      Authorization: "Bearer {{ master_access_token }}"
    status_code: 200
  register: membership_check
  until:
    - membership_check.status == 200
    - membership_check.json.value | default([]) | selectattr('id', 'equalto', ocp4_workload_ols_azure_group_id) | list | length > 0
  retries: 12
  delay: 5
  failed_when: false  # Don't fail if group membership isn't found immediately

- name: Get Token for Child App
  uri:
    url: "https://login.microsoftonline.com/{{ ocp4_workload_ols_azure_tenant_id }}/oauth2/v2.0/token"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body_format: form-urlencoded
    body:
      grant_type: client_credentials
      client_id: "{{ _child_app_id }}"
      client_secret: "{{ _child_client_secret }}"
      scope: https://cognitiveservices.azure.com/.default
  register: child_token_response
  until: child_token_response is succeeded
  retries: 3
  delay: 5

- name: Set Child Access Token
  set_fact:
    _child_access_token: "{{ child_token_response.json.access_token }}"

- name: Verify Token Works with AI Service
  uri:
    # yamllint disable rule:line-length
    url: "{{ ocp4_workload_ols_llm_providers_url }}openai/deployments/{{ ocp4_workload_ols_llm_deploymentname }}/chat/completions?api-version={{ ocp4_workload_ols_azure_api_version }}"
    # yamllint enable rule:line-length
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ _child_access_token }}"
    body:
      messages:
        - role: system
          content: "You are a helpful assistant."
        - role: user
          content: "What is the largest city in India?"
      max_tokens: 100
    body_format: json
  register: ai_service_response
  until: ai_service_response is succeeded
  retries: 3
  delay: 5

- name: Display AI Service Response
  debug:
    msg: "AI service test successful - token is valid"
  when: ocp4_workload_ols_debug | default(false)
